window.PHX_SITE_DEFAULTS = {
  heroEyebrow: 'PHOENIX BRANCH AGREEMENT',
  heroTitle: 'THỎA THUẬN TIẾP NHẬN NHÁNH',
  heroSubtitle: 'Biên bản điện tử xác nhận một Quân Đoàn trở thành nhánh trực thuộc hệ thống PHOENIX',
  sourceLabel: 'BÊN ĐƯỢC TIẾP NHẬN',
  targetLabel: 'SAU KHI XÁC NHẬN',
  mainLegion: 'PHOENIX 禄',
  sourceLegion: 'TB● Warriors',
  targetBranch: 'PHOENIX 禄 — Nhánh 3',
  branchBadge: 'NHÁNH 3',
  ownerUid: '2186899354',
  partyALogoUrl: 'assets/logo.png',
  partyBLogoUrl: '',
  agreementTitle: 'THỎA THUẬN TIẾP NHẬN & THÀNH LẬP NHÁNH',
  agreementSubtitle: 'Biên bản xác nhận điện tử giữa hai Quân Đoàn',
  notice: 'Quân Đoàn được tiếp nhận giữ nguyên cộng đồng thành viên hiện có và trở thành một nhánh trực thuộc Quân Đoàn chính. Đây là thay đổi về cơ cấu, tên nhánh và quyền quản lý; không phải chuyển thành viên sang một Quân Đoàn khác.',
  termsHeading: 'Điều khoản thỏa thuận',
  term1Title: 'Nội dung tiếp nhận',
  term1Body: 'Hai bên thống nhất tiếp nhận Quân Đoàn TB● Warriors vào hệ thống PHOENIX 禄 và tổ chức thành PHOENIX 禄 — Nhánh 3.\nNhánh giữ nguyên cộng đồng thành viên hiện có; việc tiếp nhận không đồng nghĩa với chuyển thành viên sang một Quân Đoàn khác.\nNhánh hoạt động trong cơ cấu chung và chịu sự quản lý theo thỏa thuận này.',
  term2Title: 'Cam kết hoạt động lâu dài',
  term2Body: 'Duy trì hoạt động lâu dài và ổn định.\nKhông tự ý tách nhánh khỏi hệ thống hoặc sáp nhập với tổ chức khác khi chưa có thống nhất.\nKhông lôi kéo thành viên rời khỏi hệ thống và phối hợp với các nhánh khác.',
  term3Title: 'Kỷ luật',
  term3Body: 'Thành viên Nhánh phải tuân thủ nội quy chung.\nKhông gây mất đoàn kết, phá hoạt động chung, lạm dụng quyền quản lý hoặc làm ảnh hưởng uy tín hệ thống.\nHình thức xử lý: Nhắc nhở → Cảnh cáo → Hạ quyền → Loại khỏi Nhánh → Loại khỏi hệ thống.',
  term4Title: 'Quyền và trách nhiệm của Nhánh',
  term4Body: 'Được sử dụng tên nhánh đã thống nhất, duy trì bộ máy quản lý theo phân quyền, tham gia hoạt động chung và đóng góp ý kiến.\nQuản lý Nhánh có trách nhiệm quản lý thành viên, duy trì hoạt động, kỷ luật, báo cáo vấn đề quan trọng và phối hợp với các nhánh khác.',
  term5Title: 'Giải quyết tranh chấp',
  term5Body: 'Mọi vấn đề ưu tiên giải quyết bằng trao đổi nội bộ.\nKhông tự ý hành động gây ảnh hưởng đến Quân Đoàn, thành viên hoặc uy tín chung.\nCác vấn đề liên quan toàn hệ thống được xử lý theo cơ cấu quản lý đã thống nhất.',
  term6Title: 'Xác nhận điện tử',
  term6Body: 'Người đại diện Bên được tiếp nhận xác nhận có quyền đại diện hoặc được ủy quyền, đã đọc toàn bộ nội dung và đồng ý với thỏa thuận.\nNgay sau khi xác nhận, hệ thống tạo mã hồ sơ và bản thỏa thuận điện tử. Không yêu cầu Bên PHOENIX ký lại trên hệ thống.',
  formEyebrow: 'XÁC NHẬN ĐIỆN TỬ',
  formTitle: 'Thông tin người đại diện Bên được tiếp nhận',
  formNote: 'Sau khi bấm xác nhận, hệ thống sẽ tạo ngay bản thỏa thuận điện tử có mã hồ sơ riêng. Nội dung của hồ sơ được khóa theo phiên bản thỏa thuận tại thời điểm xác nhận.',
  confirmStructureText: 'Tôi đồng ý với cơ cấu tiếp nhận và tên nhánh được nêu trong thỏa thuận.',
  confirmLongTermText: 'Tôi cam kết hoạt động lâu dài theo các điều khoản đã công bố.',
  confirmDisciplineText: 'Tôi đồng ý với quy định kỷ luật và cơ chế quản lý đã nêu.',
  confirmRightsText: 'Tôi đã hiểu quyền và trách nhiệm của Nhánh trực thuộc.',
  confirmFinalText: 'Tôi xác nhận có quyền đại diện/được ủy quyền, đã đọc toàn bộ thỏa thuận và thông tin cung cấp là chính xác.',
  submitButtonText: 'XÁC NHẬN & TẠO THỎA THUẬN ĐIỆN TỬ',
  footerLeft: 'PHOENIX 禄',
  footerRight: 'ELECTRONIC BRANCH AGREEMENT'
};
