window.PHX_SITE_DEFAULTS = {
  heroEyebrow: 'PHOENIX BRANCH AGREEMENT',
  heroTitle: 'PHOENIX 禄',
  heroSubtitle: 'Thỏa thuận tiếp nhận quân đoàn thành nhánh trực thuộc',
  sourceLabel: 'Quân đoàn được tiếp nhận',
  sourceLegion: 'TB● Warriors',
  targetLabel: 'Sau khi ký kết',
  targetBranch: 'PHOENIX 禄 — Nhánh 3',
  mainLegion: 'PHOENIX 禄',
  branchBadge: 'NHÁNH 3',
  ownerUid: '2186899354',
  notice: 'TB● Warriors được giữ nguyên cộng đồng thành viên hiện có và được tiếp nhận nguyên trạng để trở thành PHOENIX 禄 — Nhánh 3. Đây là thay đổi về tên, cơ cấu và quyền quản lý; không phải chuyển thành viên sang một quân đoàn khác. Chủ Quân Đoàn hiện tại của TB● Warriors chuyển sang vị trí quản lý Nhánh 3 và tiếp tục hỗ trợ điều hành nhánh.',
  termsHeading: 'Thỏa thuận tiếp nhận & thành lập Nhánh 3',
  term1Title: 'Nội dung tiếp nhận',
  term1Body: 'Hai bên thống nhất việc PHOENIX 禄 tiếp nhận Quân Đoàn TB● Warriors để tổ chức này trở thành một nhánh trực thuộc trong hệ thống PHOENIX 禄.\nTB● Warriors được đổi tên/định danh thành PHOENIX 禄 — Nhánh 3.\nToàn bộ thành viên tiếp tục ở trong chính quân đoàn hiện tại; không có yêu cầu chuyển thành viên sang một quân đoàn khác.\nSử dụng tên chung PHOENIX 禄 và số 3 để phân biệt.\nUID 2186899354 giữ vị trí Chủ Quân Đoàn.\nChủ QĐ hiện tại của TB● Warriors chuyển sang vai trò quản lý Nhánh 3.\nNhánh 3 hoạt động trong cơ cấu chung và chịu sự quản lý của Chủ Quân Đoàn.',
  term2Title: 'Cam kết hoạt động lâu dài',
  term2Body: 'Duy trì hoạt động lâu dài.\nKhông tự ý tách Nhánh 3 khỏi PHOENIX 禄.\nKhông tự ý sáp nhập với quân đoàn/tổ chức khác.\nKhông tự ý lôi kéo thành viên rời khỏi hệ thống.\nPhối hợp với Chủ Quân Đoàn và các nhánh khác.\nBáo cáo các vấn đề quan trọng.',
  term3Title: 'Kỷ luật',
  term3Body: 'Thành viên Nhánh 3 phải tuân thủ nội quy chung. Không được gây mất đoàn kết, phá hoạt động chung, chống quyết định quản lý hợp lệ, lôi kéo thành viên, làm ảnh hưởng uy tín PHOENIX 禄, lạm dụng quyền hoặc tự ý quyết định vấn đề ảnh hưởng toàn Quân Đoàn.\nNhắc nhở → Cảnh cáo → Hạ quyền → Loại khỏi Nhánh 3 → Loại khỏi Quân Đoàn',
  term4Title: 'Quyền và trách nhiệm Nhánh 3',
  term4Body: 'Quyền: sử dụng tên PHOENIX 禄 — Nhánh 3, duy trì bộ máy quản lý theo phân quyền, tham gia hoạt động chung và đóng góp ý kiến.\nTrách nhiệm quản lý: quản lý thành viên, duy trì hoạt động và kỷ luật, báo cáo vấn đề quan trọng, phối hợp với các nhánh khác.',
  term5Title: 'Giải quyết tranh chấp',
  term5Body: 'Mọi vấn đề ưu tiên giải quyết bằng trao đổi nội bộ. Không tự ý hành động gây ảnh hưởng đến Quân Đoàn, thành viên hoặc uy tín chung. Các vấn đề liên quan toàn hệ thống thuộc quyền quyết định của Chủ Quân Đoàn theo cơ cấu đã thống nhất.',
  term6Title: 'Xác nhận',
  term6Body: 'Người đại diện TB● Warriors xác nhận có quyền đại diện hoặc được ủy quyền; đã đọc toàn bộ nội dung; đồng ý việc TB● Warriors trở thành PHOENIX 禄 — Nhánh 3, đồng ý cơ cấu quản lý, hoạt động lâu dài và kỷ luật; đồng thời xác nhận thông tin cung cấp là chính xác. Sau khi Bên TB● Warriors ký, đại diện PHOENIX 禄 sẽ ký xác nhận tại trang quản trị để hoàn tất thỏa thuận hai bên.',
  formEyebrow: 'THỎA THUẬN HAI BÊN',
  formTitle: 'Xác nhận của người đại diện TB● Warriors',
  formNote: 'Thông tin dưới đây dùng để xác nhận người đại diện và quy mô hiện tại của quân đoàn, không phải danh sách thành viên chuyển sang quân đoàn khác.',
  confirmStructureText: 'Tôi đồng ý cơ cấu quản lý: TB● Warriors được tiếp nhận nguyên trạng để trở thành PHOENIX 禄 — Nhánh 3; UID 2186899354 giữ vị trí Chủ Quân Đoàn của Nhánh 3 theo thỏa thuận.',
  confirmLongTermText: 'Tôi cam kết Nhánh 3 hoạt động lâu dài và không tự ý tách khỏi hệ thống PHOENIX 禄.',
  confirmDisciplineText: 'Tôi đồng ý quy định kỷ luật và các hình thức xử lý đã nêu.',
  confirmRightsText: 'Tôi đã hiểu quyền và trách nhiệm của Nhánh 3.',
  confirmFinalText: 'Tôi xác nhận có quyền đại diện/được ủy quyền, đã đọc toàn bộ thỏa thuận và thông tin cung cấp là chính xác.',
  submitButtonText: 'KÝ XÁC NHẬN BÊN TB● WARRIORS',
  footerLeft: 'PHOENIX 禄',
  footerRight: 'BRANCH AGREEMENT PORTAL'
};
